// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AuthorizedHeader: typeof import('./src/components/Header/AuthorizedHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    MovieDetails: typeof import('./src/components/MovieDetails/MovieDetails.vue')['default']
    MovieLabels: typeof import('./src/components/MovieLabels/MovieLabels.vue')['default']
    MovieSlider: typeof import('./src/components/MovieSlider/MovieSlider.vue')['default']
    MovieSliderItem: typeof import('./src/components/MovieSliderItem/MovieSliderItem.vue')['default']
    ProfileDropdown: typeof import('./src/components/ProfileDropdown/ProfileDropdown.vue')['default']
    Slider: typeof import('./src/components/Slider/Slider.vue')['default']
    Spinner: typeof import('./src/components/Spinner/Spinner.vue')['default']
    UnauthorizedHeader: typeof import('./src/components/Header/UnauthorizedHeader.vue')['default']
  }
}

export { }
