// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    Slider: typeof import('./src/components/Slider/Slider.vue')['default']
    Spinner: typeof import('./src/components/Spinner/Spinner.vue')['default']
  }
}

export { }
