// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AuthorizedHeader: typeof import('./src/components/Header/AuthorizedHeader.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    MovieDetails: typeof import('./src/components/MovieDetails/MovieDetails.vue')['default']
    MovieLabels: typeof import('./src/components/MovieLabels/MovieLabels.vue')['default']
    MovieSlider: typeof import('./src/components/MovieSlider/MovieSlider.vue')['default']
    MovieSliderItem: typeof import('./src/components/MovieSliderItem/MovieSliderItem.vue')['default']
    ProfileDropdown: typeof import('./src/components/ProfileDropdown/ProfileDropdown.vue')['default']
    Slider: typeof import('./src/components/Slider/Slider.vue')['default']
    Spinner: typeof import('./src/components/Spinner/Spinner.vue')['default']
    UnauthorizedHeader: typeof import('./src/components/Header/UnauthorizedHeader.vue')['default']
  }
}

export { }
