// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./src/components/Header/AdminHeader.vue')['default']
    AuthorizedHeader: typeof import('./src/components/Header/AuthorizedHeader.vue')['default']
    'AuthorizedHeader copy': typeof import('./src/components/Header/AuthorizedHeader copy.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MovieDetails: typeof import('./src/components/MovieDetails/MovieDetails.vue')['default']
    MovieLabels: typeof import('./src/components/MovieLabels/MovieLabels.vue')['default']
    MovieList: typeof import('./src/components/MovieList/MovieList.vue')['default']
    MovieListItem: typeof import('./src/components/MovieListItem/MovieListItem.vue')['default']
    MovieSlider: typeof import('./src/components/MovieSlider/MovieSlider.vue')['default']
    MovieSliderItem: typeof import('./src/components/MovieSliderItem/MovieSliderItem.vue')['default']
    Pagination: typeof import('./src/components/Pagination/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/Slider/Slider.vue')['default']
    Spinner: typeof import('./src/components/Spinner/Spinner.vue')['default']
    UnauthorizedHeader: typeof import('./src/components/Header/UnauthorizedHeader.vue')['default']
  }
}

export {}
